### ISSUE TITLE
genericsetup hides collective.flowplayer

### ISSUE THREAD

**Issue by Rudd-O** [collective/collective.blog.star#1]
when blog.star is in the buildout, its setup profile hides collective.flowplayer from installation, and even when blog.star is actually installed, collective.flowplayer is unavailable for use.

I had to resort to undoing the install.  it was a bit problematic.

**Comment by regebro** [comment]
collective.flowplayer should be hidden by blog.star and installed when blog.star is installed. Blog star is the "collection" of packages, which allows you to treat it as one application. The bug here in that case is that collective.flowplayer was not installed when you installed blog.star.

**Comment by Rudd-O** [comment]
No, Lennart.  _This_ bug isn't that collective.flowplayer failed to be installed upon blog.star installation.  That's a separate bug -- if you want me to, I can file a bug for that too.

This bug here is that blog.star hides collective.flowplayer.  That is the bug that I am reporting here.

Let me explain how exactly this behavior of blog.star is a bug that causes problems.

I had site A and site B, where I was going to install only flowplayer on site A and blog.star (along with all its dependencies) on site B.  I didn't want blog.star on both sites.  I wanted it only on site B.  The problem is that, once I added blog.star to the buildout, that action wasn't possible anymore.  Merely adding blog.star to the buildout _hid_ collective.flowplayer from the Quickinstaller on _both_ site setups.

I wasted an _hour_ trying to figure out that blog.star was the thing blocking me from installing only flowplayer on site A.  Of course, as soon as I found out what the problem was -- several other people around the Web have also been bitten by it -- since blog.star was causing this problem for me, I decided I'd rather not use it and took it out of the buildout.

---

I've noticed this trend in Plone add-ons: an increasing number of add-ons incorrectly assume that just being in the buildout means that the functionality of the package should be made available immediately to all Plones in the instance (collective.feeds), or that the behavior of all Plones needs to be modified whether the user wants it or not (hiding third-party add-ons).

This is the same grave mistake that the old Zope Products model had -- a mistake that we tried to get away from by inventing GenericSetup, so that functionality could be enabled on a per-site basis rather than on a per-application-server basis.  This isn't just a "oh, we don't support your usecase" -- running multiple Plone sites from the same Zope instance is a _supported use case_, and also a practical necessity on machines that don't have truckloads of RAM.  Not everybody has several hundred dollars in cash every month to run several memory-hungry Zopes and add X to this buildout, and Y to this other buildout.

There are lots of people out there -- including me -- who are running several Plone sites in a single Zope instance or ZEO instance.  It's not cool to make a package that alters the behavior of ALL sites without first consulting me to install it on the desired sites.  Whether that behavior is hiding available products for installation or adding functionality without going through the Quickinstaller.

---

I don't want packages to be "installed" without my permission.  And I also don't want packages to be _unexpectedly hidden_ without my permission.  It costs me, and other people, time when a package breaks established convention, or breaks the UI of other packages.

Can you please fix this bug and make it so blog.star doesn't hide collective.flowplayer?  Thanks in advance.  We will deal with the other bugs I mentioned here separately.

**Comment by regebro** [comment]
If you don't want all packages as a bundle, don't use the collective.blog.star. The collective.blog.star package contains no functionality, it only bundles the other packages together for simplicity. All the functionality are in other packages, which you instead can then add to your buildout separately.

This is documented and intended behavior. So this is not a bug, it is a feature.

**Comment by Rudd-O** [comment]
So what if I want to use the blog.star package in one site but not the other, and both are in the same Zope server?

Am I doomed to use blog.star in both or no sites in the same Zope server?  What if I want to install blog.star in one site, but only collective.flowplayer in the other?  Your code will continue to hide flowplayer as long as your code is in the buildout.  Am I screwed?

Is this not a bug?  Your response is less than satisfactory and does not address any of my observations, which I took the time to elaborate on.  I expected better from you, Lennart.

I guess this mindset partly explains why WordPress, being the PHP crap that it is, has 50% of the CMS market.

**Comment by regebro** [comment]
No, you are not screwed. Once again, the blog.star package provides absolutely no functionality whatsoever. It's just an easy way to install a bunch of parts. If you rather want to install all the parts separately, then don't use the blog.star package, just use the separate parts.

**Comment by Rudd-O** [comment]
OK, I've tried to make my point twice but it clearly hasn't come across, since you actually keep responding to a different issue which I have no problems with.  Maybe I'm not communicating my concern correctly, or whatever.  I'm sorry we couldn't communicate better to you the notion that installing blog.star in the buildout shouldn't influence the behavior of _all_ the Plone instances running from that buildout.

In any case, this is going nowhere, so I'll stop here.  Good bye.

**Comment by regebro** [comment]
You have made yourself perfectly clear, and I understand your use case and have told you how to solve it. You seem however not to recognize this, so I don't know what the problem is now.

You don't want to treat blog.star as a monolithic software. You want to choose which parts you install in which sites. And then, I now tell you for the third time: Don't add collective.blog.star to your buildout. Add instead all the packages that it depends on. Then you can choose which ones to install and not to install, and your problem is solved.

Your request; that collective.blog.star doesn't hide the packages it installs is not going to happen. That's the whole point of collective.blog.star. Essentially that's all it does. It clumps these other packages together into one, including hiding them. That's not what you want. So don't use it.
