### ISSUE TITLE
Losing am/pm setting for events when collective.blog.star installed

### ISSUE THREAD

**Issue by johnlawson** [collective/collective.blog.star#4]
I have a weird bug which is affecting  start and end times for Plone events  - they are losing their am and pm setting.

I have established the problem for me is caused  by collective.blog.star - when I remove it from  the eggs section in buildout.cfg, the  events are showing the correct am and pm setting.

I was wondering if anybody else has encountered this problem.

Thanks...

**Comment by regebro** [comment]
Can you explain what the "am and pm setting" is in more detail? Does it switch from am to pm, or?

**Comment by johnlawson** [comment]
Hi,
the "am and pm setting" are fields  in the core Plone event content type, "Event Starts" and "Event Ends".
With collective.blog.star installed, the event loses the am/pm setting and only displays "--", and does not allow  am or pm to be saved, it is only ever showing "--".  Remove collective.blog.star from buildout and the core Event content type behaves normally.

**Comment by johnlawson** [comment]
Hi Lennar, I replied on the github page, don't know if that was the best place to post my reply. The am and pm settings are in the core Plone Event content type, in the start and stop time fields. collective.blog.star appears to interfere with the am/pm settings for events.The event start and stop times show  -- instead of am or pm and do not allow the field to be updated. Works ok when collective.blog.star not installed.   I am only experiencing the issue on a specific server ( production unfortunately), unable to replicate the problem on other servers.   Regards, John LawsonIT Section LeaderDundee City Council Downfield House East School Road Dundee DD3 8NX 01382-438169john.lawson@dundeecity.gov.uk -----Lennart Regebro notifications@github.com wrote: ----- 
To: "collective/collective.blog.star" collective.blog.star@noreply.github.comFrom: Lennart Regebro notifications@github.comDate: 04/06/2013 03:48AMCc: John Lawson john.lawson@dundeecity.gov.ukSubject: Re: [collective.blog.star] Losing am/pm setting for events when collective.blog.star installed (#4)Can you explain what the "am and pm setting" is in more detail? Does it switch from am to pm, or?—Reply to this email directly or view it on GitHub.

**Comment by regebro** [comment]
This is the correct place.

**Comment by regebro** [comment]
I can't replicate this, perhaps there are more parameters involved.
